POST http://localhost:5000/wallet/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NmZmMGU0LTYzMzQtNDhmZi04ZDA5LWE5YjU5OTM1Y2ZiYSIsImlhdCI6MTc2ODExNTM1NCwiZXhwIjoxNzY4MTE4OTU0fQ.qFjpKK1GvXwuCSPIrq4P9iocZUXG-l39iGcwPNtHixc

{
  "toUserId": "36fc7072-599e-4d54-867a-6f4ee6935b96",
  "fromUserId" : "056ff0e4-6334-48ff-8d09-a9b59935cfba",
  "amount": 500
}


###
GET http://localhost:5000/wallet/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA1NmZmMGU0LTYzMzQtNDhmZi04ZDA5LWE5YjU5OTM1Y2ZiYSIsImlhdCI6MTc2ODExNTM1NCwiZXhwIjoxNzY4MTE4OTU0fQ.qFjpKK1GvXwuCSPIrq4P9iocZUXG-l39iGcwPNtHixc

